Algoritmo "cadastro_livro"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Cássio Eduardo Mereles
// Data atual  : 9/8/2026
Var
// Seção de Declarações das variáveis 
      autor: caracter
      cont: inteiro
      resposta: logico
Inicio

      cont<-0

      resposta<-verdadeiro

      
      enquanto (resposta=verdadeiro) faca

         escreva ("Nome do autor: ")
         leia(autor)
      
      cont<-cont+1
      
      escreva("cadastrar mais um livro?")
      leia (resposta)
      
      fimenquanto


Fimalgoritmo